name = input("Enter your name : ")
branch = input("Enter your branch : ")
gender = input("Enter your gender : ")
college = input("Enter your college name : ")
age = input("Enter your age : ")

print("\n NAME :",name)
print("\n BRANCH :",branch)
print("\n GENDER :",gender)
print("\n COLLEGE :",college)
print("\n AGE :",age)
